name: Deploy Preview

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: deploy-site-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ente-io/ente
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.com/

      - name: Patch Next.js basePath
        run: |
          sed -i.bak 's#output: "export",#basePath: process.env.NEXT_PUBLIC_BASE_PATH,output: "export",#i' web/packages/base/next.config.base.js

      - name: Install dependencies
        run: cd web && yarn

      - name: Build
        run: cd web && yarn build
        env:
          NEXT_PUBLIC_ENTE_ENDPOINT: https://ente.tianhaoltd.top/api
          NEXT_PUBLIC_BASE_PATH: /ente-group

      - name: Deploy to Doc Repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web/apps/photos/out
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com